# Generated by Django 4.1.4 on 2023-04-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_name', models.CharField(max_length=30)),
                ('listing_desc', models.CharField(max_length=100)),
                ('imgurl', models.ImageField(default='https://icon-library.com/images/no-picture-available-icon/no-picture-available-icon-1.jpg', null=True, upload_to='')),
            ],
        ),
    ]
