# Generated by Django 4.1.4 on 2023-04-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_imgurl_alter_listing_listing_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='starting_bid',
            field=models.IntegerField(default=0),
        ),
    ]
