# Generated by Django 4.1.4 on 2023-04-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_created_at_listing_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='updated_at',
        ),
    ]
