# Generated by Django 4.1.4 on 2023-04-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_listing_user_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user_created',
            field=models.CharField(default='mathewalex', max_length=50),
        ),
    ]
