# Generated by Django 4.1.4 on 2023-04-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_listing_user_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='user_created',
        ),
    ]
