# Generated by Django 4.1.4 on 2023-04-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_desc',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_name',
            field=models.CharField(max_length=70),
        ),
    ]
