# Generated by Django 4.1.4 on 2023-04-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
