# Generated by Django 4.1.4 on 2023-04-07 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_remove_watchlist_id_alter_watchlist_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
